#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Pygments
Version  : 2.0.2
Release  : 12
URL      : https://pypi.python.org/packages/source/P/Pygments/Pygments-2.0.2.tar.gz
Source0  : https://pypi.python.org/packages/source/P/Pygments/Pygments-2.0.2.tar.gz
Summary  : Pygments is a syntax highlighting package written in Python.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: Pygments-bin
Requires: Pygments-python
BuildRequires : nose
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
phpMyAdmin can manage a whole MySQL-server (needs a super-user) but
also a single database. To accomplish the latter you'll need a
properly set up MySQL-user which can read/write only the desired
database. It's up to you to look up the appropiate part in the MySQL
manual. Currently phpMyAdmin can:
  - create and drop databases
  - create, copy, drop and alter tables
  - delete, edit and add fields
  - execute any SQL-statement, even batch-queries
  - manage keys on fields
  - load text files into tables
  - create (*) and read dumps of tables
  - export (*) and import data to CSV values
  - administer multiple servers and single databases
  - check referencial integrity
  - create complex queries automatically connecting required tables
  - create PDF graphics of your database layout
  - communicate in more than 38 different languages

%package bin
Summary: bin components for the Pygments package.
Group: Binaries

%description bin
bin components for the Pygments package.


%package python
Summary: python components for the Pygments package.
Group: Default
Provides: pygments-python

%description python
python components for the Pygments package.


%prep
%setup -q -n Pygments-2.0.2

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make test
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pygmentize

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
